package com.ps.contactmanager.domain.enums;

public enum ERROR_CODE {
    BAD_REQUEST("BAD_REQUEST"),
    EXPECTED_EXTENSION("EXPECTED_EXTENSION"),
    FILE_LARGE_SIZE("FILE_LARGE_SIZE"),
    TASK_RUNNING("TASK_RUNNING"),
    TASK_ALREADY_DONE("TASK_ALREADY_DONE"),
    TASK_ALREADY_CANCELLED("TASK_ALREADY_CANCELLED"),
    TASK_ALREADY_SCHEDULED("TASK_ALREADY_SCHEDULED"),
    API_AUTHENTICATE_FAILED("API_AUTHENTICATE_FAILED"),
    API_GET_EQUIPMENT_FAILED("API_GET_EQUIPMENT_FAILED"),
    API_GET_COMPANY_FAILED("API_GET_COMPANY_FAILED"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    INVALID_URL("INVALID_URL"),
    OBJ_NOT_FOUND("OBJ_NOT_FOUND"),
    INEXISTANT_CHECK_LIST("INEXISTANT_CHECK_LIST"),
    TOTAL_AMOUNT_EQUIPMENT_INF("TOTAL_AMOUNT_EQUIPMENT_INF"),
    TOTAL_AMOUNT_EQUIPMENT_SUP("TOTAL_AMOUNT_EQUIPMENT_SUP"),
    NOT_LOGGED("NOT_LOGGED"),
    UNAUTHORIZED_REQUEST("UNAUTHORIZED_REQUEST"),
    UNAUTHORIZED_COMMENT("UNAUTHORIZED_COMMENT"),
    SIMULATOR_SETTINGS_CHANGED("SIMULATOR_SETTINGS_CHANGED"),
    INCORRECT_PASSWORD("INCORRECT_PASSWORD"),
    INCORRECT_EMAIL("INCORRECT_EMAIL"),
    USERNAME_LOCKED("USERNAME_LOCKED"),
    USER_BLOCKED("USER_BLOCKED"),
    CODE_FREELANCE_TVA("CODE_FREELANCE_TVA"),
    REQUIRED("REQUIRED"),
    INCORRECT_USERNAME_OR_PASSWORD("INCORRECT_USERNAME_OR_PASSWORD"),
    USER_ALREADY_AFFECTED("USER_ALREADY_AFFECTED"),
    USERNAME_EXISTS("USERNAME_EXISTS"),
    UNAUTHORIZED("UNAUTHORIZED"),
    ALREADY_SUBMITTED("ALREADY_SUBMITTED"),
    INEXISTANT_USER("INEXISTANT_USER"),
    INEXISTANT_LEGAL_FORM("INEXISTANT_LEGAL_FORM"),
    REFERENCED_COMPANY("REFERENCED_COMPANY"),
    INVALID_SESSION("INVALID_SESSION"),
    MISSING_HEADER("MISSING_HEADER"),
    TECHNICAL_EXCEPTION("TECHNICAL_EXCEPTION"),
    BACKEND_TECHNICAL_EXCEPTION("BACKEND_TECHNICAL_EXCEPTION"),
    PHONE_NUMBER_INVALID("PHONE_NUMBER_INVALID"),
    EXPIRED_TOKEN("EXPIRED_TOKEN"),
    INVALID_PWD("INVALID_PWD"),
    INVALID_PWD_SAME_OLD("INVALID_PWD_SAME_OLD"),
    INEXISTANT_PROFILE("INEXISTANT_PROFILE"),
    INEXISTANT_EQUIPMENT("INEXISTANT_EQUIPMENT"),
    INEXISTANT_SIMULATION("INEXISTANT_SIMULATION"),
    INEXISTANT_COMMENT("INEXISTANT_COMMENT"),
    INEXISTANT_AGENCY("INEXISTANT_AGENCY"),
    COMMENT_OWNER("COMMENT_OWNER"),
    EMAIL_EXISTS("EMAIL_EXIST"),
    INEXISTANT_CONTACT("INEXISTANT_CONTACT"),
    DIFFERENT_TOKEN("DIFFERENT_TOKEN"),
    TOKEN_NOT_FOUND("TOKEN_NOT_FOUND"),
    ATTRIBUTED_PROFILE("ATTRIBUTED_PROFILE"),
    INEXISTANT_PRIVILEGE("INEXISTANT_PRIVILEGE"),
    INEXISTANT_COMPANY("INEXISTANT_COMPANY"),
    INEXISTANT_SETTINGS("INEXISTANT_SETTINGS"),
    TOKEN_ALREADY_VALID("TOKEN_ALREADY_VALID"),
    CODE_EXISTS("CODE_EXISTS"),
    NAME_EXISTS("NAME_EXISTS"),
    ATTRIBUTED_COLOR("ATTRIBUTED_COLOR"),
    REFERENCED_USER("REFERENCED_USER"),
    RECOVERY_ALREADY_DONE("RECOVERY_ALREADY_SENT"),
    STATUS_ALREADY_SAME("STATUS_ALREADY_SAME"),
    EMPTY_PRIVILEGES_LIST("EMPTY_PRIVILEGES_LIST"),
    RADICAL_EXISTS("RADICAL_EXISTS"),
    RS_EXISTS("RS_EXISTS"),
    NIF_EXISTS("NIF_EXISTS"),
    RC_EXISTS("RC_EXISTS"),
    ERR_EMPTY_FIELD("ERR_EMPTY_FIELD"),
    ERR_ALPHA_NUM_FIELD("ERR_ALPHA_NUM_FIELD"),
    ERR_DUPLICATE_KEY("ERR_DUPLICATE_KEY"),
    ERR_FORMAT_NUM("ERR_FORMAT_NUM"),
    ERR_INV_LNG_DETAILED("ERR_INV_LNG_DETAILED"),
    ERR_INV_LNG("ERR_INV_LNG"),
    UNSENT_MAIL("UNSENT_MAIL"),
    INVALID_PWD_FROM_OLD("INVALID_PWD_FROM_OLD"),
    INVALID_TAUX("INVALID_TAUX"),
    INVALID_STEPPER_LEASING_DURATION("INVALID_STEPPER_LEASING_DURATION"),
    INVALID_MIN_LEASING_DURATION("INVALID_MIN_LEASING_DURATION"),
    MIN_OVER_MAX_LEASING_DURATION("MIN_OVER_MAX_LEASING_DURATION"),
    MIN_OVER_MAX_LEASING_AMOUNT("MIN_OVER_MAX_LEASING_AMOUNT"),
    MISSED_RESIDUAL_VALUE("MISSED_RESIDUAL_VALUE"),
    TWO_RESIDUAL_VALUE_DEFINED("TWO_RESIDUAL_VALUE_DEFINED"),
    INVALID_HIP("INVALID_HIP"),
    INEXISTANT_REQUEST("INEXISTANT_REQUEST"),

    INEXISTANT_TASK("INEXISTANT_TASK"),
    MIN_OVER_MAX_HIP("MIN_OVER_MAX_HIP"),
    PAST_DATE("PAST_DATE"),
    ERR_EMPTY_DATA("ERR_EMPTY_DATA"),
    VALUE_EXISTS("VALUE_EXISTS"),
    CODE_AGENCE_EXISTS("CODE_AGENCE_EXISTS");


    private String value;

    ERROR_CODE(String value, String message) {
        this.value = value;
        this.message = message;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return this.getValue();
    }


    private final String message;

    ERROR_CODE(String message) {
        this.message = message;
    }

    public String getMessage() {
        // parse params
            return message;
    }

}
